# Ansible demo for reusing an existing ArcGIS Server volume
# (see ansible_install_arcpy.yml playbook) to restart a remote virtual machine
# on CSC's cPouta and running simple ArcPy script.
#
# You'll need to have your Ansible environment properly setup and modify
# the Ansible variables to your own:
#    - NAME_OF_YOUR_KEY: the name of the key pair as seen in your cPouta project
#    - NAME_OF_YOUR_SECURITY_GROUP: the name of a security group as seen in your cPouta project
#
# This Ansible script assumes that you have the "test_data" folder in the same
# directory where this Ansible script is. This is how those are defined in the code:
#     test_data_dir: test_data
#     demo_script: my_arcpy_script.py
#
# The script copies the "test_data" folder to the remote virtual machine,
# then executes the example "my_arcpy_script.py" Python script and copies the
# results to the local machine to the subfolder "test_data/results".
#Then the remote "test_data" folder is removed and the virtual machine is deleted.
---
- name: Create virtual machine from existing ArcGIS Server on cPouta
  hosts: localhost # The OpenStack modules run on your local machine.
  connection: local
  vars:
    demo_key: NAME_OF_YOUR_KEY
    demo_sg: NAME_OF_YOUR_SECURITY_GROUP
    demo_security_groups: default, {{ demo_sg }}
    arcgis_server_vol: arcpy-volume
    demo_instance: test-arcpy
    cpouta_flavor: standard.tiny

  tasks:
    - name: Create a virtual machine from existing ArcGIS Server volume
      register: result
      os_server:
        name: "{{ demo_instance }}"
        flavor: "{{ cpouta_flavor }}"
        key_name: "{{ demo_key }}"
        security_groups: "{{ demo_security_groups }}"
        boot_volume: "{{ arcgis_server_vol }}"

    - name: Add new host to inventory
      add_host: name={{ result.server.public_v4 }} groups=arcpy_nodes

    - name: clear ssh known_hosts
      known_hosts: name={{ result.server.public_v4 }} state=absent
      when: result | changed

    - name: Wait for instance to be ready
      wait_for: host={{ result.server.public_v4 }} port=22 search_regex=OpenSSH delay=3

- name: Run example script in cPouta instance
  hosts: arcpy_nodes
  remote_user: cloud-user
  vars:
    test_data_dir: test_data
    demo_script: my_arcpy_script.py

  tasks:
    - synchronize:
        mode: push
        src: ./{{ test_data_dir }}/
        dest: ~/{{ test_data_dir }}/

    - name: run ArcPy script
      shell: ~/arcgis/server/tools/python ~/{{ test_data_dir }}/{{ demo_script }}

    - synchronize:
        mode: pull
        src: ~/{{ test_data_dir }}/
        dest: ./{{ test_data_dir }}/results

    - name: Delete remote directory
      file:
        state: absent
        path: ~/{{ test_data_dir }}/

- name: Destroy the computing ArcGIS Server instance (the ArcGIS Server volume remains)
  hosts: localhost
  vars:
    demo_instance: test-arcpy

  tasks:
    - name: Destroy a VM
      os_server:
        name: "{{ demo_instance }}"
        state: absent
...
